version: "3.0"

services:
  web:
    build: ./docker/frontend
    restart: always
    tty: true
    ports:
      - "80:8080"
    volumes:
      - ./frontend:/var/www/app
    links:
      - "websocket:websocket"
  websocket:
    build: ./docker/backend
    restart: always
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/var/www/app
    links:
      - "redis:redis"
  redis:
    image: redis
    ports:
      - "6379:6379"
